acronym_to_url_lookup = {
    "United States. Department of Transportation. Federal Aviation Administration": "https://ror.org/05q0y0j38",
    "United States. Department of Transportation. Federal Highway Administration": "https://ror.org/0473rr271",
    "United States. Department of Transportation. Federal Railroad Administration": "https://ror.org/0275ebj77",
    "United States. Department of Transportation. Federal Transit Administration": "https://ror.org/01mg0yh05",
    "United States. Department of Transportation. National Highway Traffic Safety Administration": "https://ror.org/04gcfqs37",
    "United States. Department of Transportation. United States Maritime Administration": "https://ror.org/055hae320",
    "United States. Department of Transportation. Volpe National Transportation Systems Center": "https://ror.org/04a2k6j28",
    "United States. Department of Transportation. Federal Motor Carrier Safety Administration": "https://ror.org/01jt5mq34",
    "United States. Department of Transportation. Bureau of Transportation Statistics": "https://ror.org/05xfdey77",
    "United States. Department of Transportation. Office of the Assistant Secretary for Research and Technology": "https://ror.org/0150hkx05",
    "United States. Department of Transportation. Intelligent Transportation Systems Joint Program Office": "https://ror.org/012cshy85",
    "United States. Department of Transportation. University Transportation Centers (UTC) Program": "https://ror.org/02jf59s11",
    "United States. Department of Transportation. National Transportation Library": "https://ror.org/00snbrd52",
    "United States. Department of Transportation. Federal Highway Administration. Turner-Fairbank Highway Research Center": "https://ror.org/04edx5729",
    "United States. Department of Transportation. Federal Aviation Administration. Office of Aviation. Civil Aerospace Medical Institute": "https://ror.org/043e04s74",
}